services:
  mongo:
    image: mongo:8.0 
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" # стандартный порт MongoDB
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  bitcoin-viewer-docker:
    container_name: bitcoin-viewer-docker
    build:
      context: ./bitcoin-hist-viewer
      dockerfile: Dockerfile
    ports:
      - "3111:3000"
    external_links:
      - mongo

  bitcoin-scraper-docker:
    container_name: bitcoin-scraper-docker
    build:
      context: ./bitcoin-hist-scraper
      dockerfile: Dockerfile
    external_links:
      - mongo

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local
